apiVersion: apps/v1
kind: Deployment
metadata:
  name: joey-otel-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joey-otel-metrics
  template:
    metadata:
      labels:
        app: joey-otel-metrics
        opentelemetry.io/name: joey-otel-metrics
    spec:
      containers:
        - name: joey-otel-metrics
          image: joeyfreeland/otel-metrics-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: joey-otel-metrics
  labels:
    opentelemetry.io/name: joey-otel-metrics
spec:
  selector:
    app: joey-otel-metrics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
